/* eslint-disable */
// Generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	isReady: () => __TAURI_INVOKE<boolean>("is_ready"),
	startupStatus: () => __TAURI_INVOKE<StartupStatus>("startup_status"),
	mobileSystemInfo: () => typedError<{
	deviceName: string,
	safeArea: SafeAreaInsets,
	displayKind: DisplayKind,
	/**  `None` while no platform publishes a documented color-panel query. */
	colorPanel: boolean | null,
} | null, CommandError>(__TAURI_INVOKE("mobile_system_info")),
	inputCapabilities: () => typedError<InputCapabilities, CommandError>(__TAURI_INVOKE("input_capabilities")),
	createHandwrittenNote: (title: string | null) => typedError<Page, CommandError>(__TAURI_INVOKE("create_handwritten_note", { title })),
	loadHandwritingNote: (pageUuid: string, editing: boolean) => typedError<InkHistorySnapshot, CommandError>(__TAURI_INVOKE("load_handwriting_note", { pageUuid, editing })),
	handwritingNoteStatus: (pageUuid: string) => typedError<InkNoteStatus, CommandError>(__TAURI_INVOKE("handwriting_note_status", { pageUuid })),
	previewHandwritingVersion: (pageUuid: string, versionUuid: string) => typedError<InkDraft, CommandError>(__TAURI_INVOKE("preview_handwriting_version", { pageUuid, versionUuid })),
	resolveHandwritingConflict: (pageUuid: string, expectedHeads: string[], keep: string[]) => typedError<string[], CommandError>(__TAURI_INVOKE("resolve_handwriting_conflict", { pageUuid, expectedHeads, keep })),
	completeAllHandwriting: () => typedError<null, CommandError>(__TAURI_INVOKE("complete_all_handwriting")),
	setHandwritingBackground: (background: boolean) => __TAURI_INVOKE<void>("set_handwriting_background", { background }),
	handwritingHistory: (pageUuid: string, redo: boolean, expectedRevision: string | null) => typedError<InkHistoryUpdate, CommandError>(__TAURI_INVOKE("handwriting_history", { pageUuid, redo, expectedRevision })),
	saveHandwritingPatch: (pageUuid: string, patch: InkDraftPatch, expectedRevision: string | null) => typedError<string, CommandError>(__TAURI_INVOKE("save_handwriting_patch", { pageUuid, patch, expectedRevision })),
	completeHandwritingNote: (pageUuid: string) => typedError<InkNoteStatus, CommandError>(__TAURI_INVOKE("complete_handwriting_note", { pageUuid })),
	setSystemBarsStyle: (darkBackground: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_system_bars_style", { darkBackground })),
	setDisplayProfile: (eink: boolean) => typedError<DisplayProfileResult, CommandError>(__TAURI_INVOKE("set_display_profile", { eink })),
	/**
	 *  Repaints the whole panel once. Partial e-ink update modes leave the previous image behind, and
	 *  nothing but a full refresh clears it.
	 */
	requestFullRefresh: () => typedError<null, CommandError>(__TAURI_INVOKE("request_full_refresh")),
	syncStatus: () => __TAURI_INVOKE<SyncStatus>("sync_status"),
	serverAiStatus: () => typedError<AiIndexStatus, CommandError>(__TAURI_INVOKE("server_ai_status")),
	saveServerAiSettings: (settings: AiRuntimeSettings) => typedError<AiIndexStatus, CommandError>(__TAURI_INVOKE("save_server_ai_settings", { settings })),
	saveServerAiProvider: (settings: AiProviderSettingsUpdate) => typedError<AiIndexStatus, CommandError>(__TAURI_INVOKE("save_server_ai_provider", { settings })),
	probeServerAiProvider: (settings: AiProviderSettingsUpdate) => typedError<AiProviderProbeResult, CommandError>(__TAURI_INVOKE("probe_server_ai_provider", { settings })),
	reindexServerAi: () => typedError<AiIndexStatus, CommandError>(__TAURI_INVOKE("reindex_server_ai")),
	loadSettings: () => typedError<SettingsSnapshot, CommandError>(__TAURI_INVOKE("load_settings")),
	exportDeviceConfiguration: (includeToken: boolean, appearance: {
	theme: ConfigurationTheme,
	palette: ConfigurationPalette,
	displayProfile?: ConfigurationDisplayProfile,
	inkColor?: ConfigurationInkColor,
} | null) => typedError<boolean, CommandError>(__TAURI_INVOKE("export_device_configuration", { includeToken, appearance })),
	previewConfigurationImport: () => typedError<{
	id: string,
	serverUrl: string | null,
	tokenIncluded: boolean,
	tokenRequired: boolean,
	search: ConfigurationSearch,
	appearance: ConfigurationAppearance | null,
} | null, CommandError>(__TAURI_INVOKE("preview_configuration_import")),
	applyConfigurationImport: (id: string, token: string | null) => typedError<ConfigurationImportResult, CommandError>(__TAURI_INVOKE("apply_configuration_import", { id, token })),
	cancelConfigurationImport: (id: string) => __TAURI_INVOKE<void>("cancel_configuration_import", { id }),
	saveSettings: (update: SettingsUpdate) => typedError<SettingsSnapshot, CommandError>(__TAURI_INVOKE("save_settings", { update })),
	resetSettings: () => typedError<SettingsSnapshot, CommandError>(__TAURI_INVOKE("reset_settings")),
	retrySync: () => __TAURI_INVOKE<void>("retry_sync"),
	/**
	 *  Puts every change the server refused back in the send queue and reconnects.
	 *  Nothing was deleted while it was held back, so this is a plain retry.
	 */
	retryRejectedChanges: () => typedError<number, CommandError>(__TAURI_INVOKE("retry_rejected_changes")),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	historyStatus: () => typedError<HistoryStatus, CommandError>(__TAURI_INVOKE("history_status")),
	undo: () => typedError<HistoryMoveResult, CommandError>(__TAURI_INVOKE("undo")),
	redo: () => typedError<HistoryMoveResult, CommandError>(__TAURI_INVOKE("redo")),
	renamePage: (uuid: string, title: string | null, expectedRevision: ContentRevision) => typedError<Page, CommandError>(__TAURI_INVOKE("rename_page", { uuid, title, expectedRevision })),
	setPageLayout: (uuid: string, layout: PageLayout) => typedError<Page, CommandError>(__TAURI_INVOKE("set_page_layout", { uuid, layout })),
	createNote: (title: string | null) => typedError<CreateNoteResult, CommandError>(__TAURI_INVOKE("create_note", { title })),
	ensureJournal: (date: JournalDate) => typedError<Page, CommandError>(__TAURI_INVOKE("ensure_journal", { date })),
	getJournal: (date: JournalDate) => typedError<{
	uuid: string,
	kind: PageKind,
	title: string | null,
	layout: PageLayout,
	titleRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
} | null, CommandError>(__TAURI_INVOKE("get_journal", { date })),
	listJournals: (beforeDate: string | null, limit: number | null) => typedError<Page[], CommandError>(__TAURI_INVOKE("list_journals", { beforeDate, limit })),
	appendToJournal: (date: JournalDate, content: BlockContent, style: BlockStyle) => typedError<Block, CommandError>(__TAURI_INVOKE("append_to_journal", { date, content, style })),
	getPage: (uuid: string) => typedError<{
	uuid: string,
	kind: PageKind,
	title: string | null,
	layout: PageLayout,
	titleRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
} | null, CommandError>(__TAURI_INVOKE("get_page", { uuid })),
	getPageDocument: (uuid: string) => typedError<{
	pageUuid: string,
	revision: DocumentRevision,
	blocks: Block[],
} | null, CommandError>(__TAURI_INVOKE("get_page_document", { uuid })),
	/**
	 *  Complete outline render input fetched behind one typed IPC boundary. The
	 *  document remains the persisted source of truth; image descriptors are a
	 *  host-derived projection used only to render authorized local resources.
	 */
	getPageRenderSnapshot: (uuid: string) => typedError<{
	document: PageDocumentSnapshot,
	images: AttachmentImageDescriptor[],
} | null, CommandError>(__TAURI_INVOKE("get_page_render_snapshot", { uuid })),
	replacePageDocument: (pageUuid: string, expectedRevision: DocumentRevision, units: DocumentUnitDraft[]) => typedError<PageDocumentSnapshot, CommandError>(__TAURI_INVOKE("replace_page_document", { pageUuid, expectedRevision, units })),
	getBlock: (uuid: string) => typedError<{
	uuid: string,
	pageUuid: string,
	parentUuid: string | null,
	orderKey: OrderKey,
	style: BlockStyle,
	markdown: string,
	markdownRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
} | null, CommandError>(__TAURI_INVOKE("get_block", { uuid })),
	setBlockContent: (uuid: string, content: BlockContent, expectedRevision: ContentRevision) => typedError<Block, CommandError>(__TAURI_INVOKE("set_block_content", { uuid, content, expectedRevision })),
	setBlockStyle: (uuid: string, style: BlockStyle) => typedError<Block, CommandError>(__TAURI_INVOKE("set_block_style", { uuid, style })),
	setTaskState: (uuid: string, taskState: TaskState) => typedError<Block, CommandError>(__TAURI_INVOKE("set_task_state", { uuid, taskState })),
	splitBlock: (uuid: string, parts: BlockContent[], expectedRevision: ContentRevision) => typedError<Block[], CommandError>(__TAURI_INVOKE("split_block", { uuid, parts, expectedRevision })),
	getContainingPage: (blockUuid: string) => typedError<{
	uuid: string,
	kind: PageKind,
	title: string | null,
	layout: PageLayout,
	titleRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
} | null, CommandError>(__TAURI_INVOKE("get_containing_page", { blockUuid })),
	neighbors: (uuid: string, depth: number) => typedError<Content[], CommandError>(__TAURI_INVOKE("neighbors", { uuid, depth })),
	searchNotes: (mode: SearchMode, query: string, limit: number, rerank: boolean | null) => typedError<SearchHit[], CommandError>(__TAURI_INVOKE("search_notes", { mode, query, limit, rerank })),
	chatStream: (history: ChatTurn[], message: string, allowWrites: boolean, activeContentUuid: string | null, requestId: string, onEvent: Channel<ChatEvent>) => typedError<string, CommandError>(__TAURI_INVOKE("chat_stream", { history, message, allowWrites, activeContentUuid, requestId, onEvent })),
	cancelChat: (requestId: string) => __TAURI_INVOKE<boolean>("cancel_chat", { requestId }),
	listPages: (filter: "notes" | "journals" | "all" | null, limit: number | null) => typedError<Page[], CommandError>(__TAURI_INVOKE("list_pages", { filter, limit })),
	deletePage: (uuid: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_page", { uuid })),
	findBacklinks: (uuid: string) => typedError<Content[], CommandError>(__TAURI_INVOKE("find_backlinks", { uuid })),
	graphSnapshot: (focusUuid: string | null) => typedError<GraphSnapshot, CommandError>(__TAURI_INVOKE("graph_snapshot", { focusUuid })),
	exportData: () => typedError<string | null, CommandError>(__TAURI_INVOKE("export_data")),
	importData: () => typedError<string | null, CommandError>(__TAURI_INVOKE("import_data")),
	logseqImportCapability: () => __TAURI_INVOKE<LogseqImportAvailability>("logseq_import_capability"),
	prepareLogseqImport: (onProgress: Channel<LogseqImportProgress>) => typedError<{
	sessionUuid: string,
	sourceName: string,
	manifestSha256: string,
	destination: LogseqImportDestination,
	blockers: LogseqImportBlocker[],
	canCommit: boolean,
	report: LogseqImportReportSummary,
} | null, CommandError>(__TAURI_INVOKE("prepare_logseq_import", { onProgress })),
	logseqImportDiagnostics: (sessionUuid: string, offset: number, limit: number) => typedError<LogseqImportDiagnosticPage, CommandError>(__TAURI_INVOKE("logseq_import_diagnostics", { sessionUuid, offset, limit })),
	commitLogseqImport: (sessionUuid: string, onProgress: Channel<LogseqImportProgress>) => typedError<LogseqImportCommitResult, CommandError>(__TAURI_INVOKE("commit_logseq_import", { sessionUuid, onProgress })),
	discardLogseqImport: (sessionUuid: string) => __TAURI_INVOKE<boolean>("discard_logseq_import", { sessionUuid }),
	createBackup: () => typedError<string, CommandError>(__TAURI_INVOKE("create_backup")),
	attachFile: (location: AttachmentOwner) => typedError<{
	uuid: string,
	owner: AttachmentOwner,
	blobHash: string,
	filename: string,
	mime: string,
	size: number,
	createdAt: number,
} | null, CommandError>(__TAURI_INVOKE("attach_file", { location })),
	listAttachments: (location: AttachmentOwner) => typedError<Attachment[], CommandError>(__TAURI_INVOKE("list_attachments", { location })),
	resolveAttachmentImages: (attachmentUuids: string[]) => typedError<AttachmentImageDescriptor[], CommandError>(__TAURI_INVOKE("resolve_attachment_images", { attachmentUuids })),
	openAttachment: (uuid: string) => typedError<null, CommandError>(__TAURI_INVOKE("open_attachment", { uuid })),
	deleteAttachment: (uuid: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_attachment", { uuid })),
	createPage: (title: string) => typedError<Page, CommandError>(__TAURI_INVOKE("create_page", { title })),
	listBlockChildren: (pageUuid: string, parentUuid: string | null) => typedError<Block[], CommandError>(__TAURI_INVOKE("list_block_children", { pageUuid, parentUuid })),
	createBlock: (pageUuid: string, parentUuid: string | null, afterUuid: string | null, style: BlockStyle, markdown: string) => typedError<Block, CommandError>(__TAURI_INVOKE("create_block", { pageUuid, parentUuid, afterUuid, style, markdown })),
	indentBlock: (uuid: string) => typedError<Block, CommandError>(__TAURI_INVOKE("indent_block", { uuid })),
	outdentBlock: (uuid: string) => typedError<Block, CommandError>(__TAURI_INVOKE("outdent_block", { uuid })),
	moveBlockUp: (uuid: string) => typedError<Block, CommandError>(__TAURI_INVOKE("move_block_up", { uuid })),
	moveBlockDown: (uuid: string) => typedError<Block, CommandError>(__TAURI_INVOKE("move_block_down", { uuid })),
	deleteBlock: (uuid: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_block", { uuid })),
	getOrCreatePageByTitle: (title: string) => typedError<Page, CommandError>(__TAURI_INVOKE("get_or_create_page_by_title", { title })),
	getPageByTitle: (title: string) => typedError<{
	uuid: string,
	kind: PageKind,
	title: string | null,
	layout: PageLayout,
	titleRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
} | null, CommandError>(__TAURI_INVOKE("get_page_by_title", { title })),
	searchPagesByTitle: (query: string, limit: number) => typedError<Page[], CommandError>(__TAURI_INVOKE("search_pages_by_title", { query, limit })),
	searchBlocksFts: (query: string, limit: number, tokenMode: SearchTokenMode) => typedError<Block[], CommandError>(__TAURI_INVOKE("search_blocks_fts", { query, limit, tokenMode })),
};

/** Events */
export const events = {
	appReady: makeEvent<StartupReadyEvent>("app:ready"),
	appStartupError: makeEvent<StartupErrorEvent>("app:startup-error"),
	domainEvent: makeEvent<DomainEventMessage>("domain:event"),
};

/* Types */
export type AiGenerationState = "building" | "active" | "retired";

export type AiIndexStatus = {
	provider: AiProviderSettings,
	generationId: string,
	generationState: AiGenerationState,
	settings: AiRuntimeSettings,
	pendingEmbeddings: number,
	failedEmbeddings: number,
	indexedDocuments: number,
	sourceDocuments: number,
	pendingExtractions: number,
	failedExtractions: number,
};

export type AiProbeCheck = {
	ok: boolean,
	message: string,
};

export type AiProviderProbeResult = {
	embeddings: AiProbeCheck,
	reranking: AiProbeCheck,
	chat: AiProbeCheck,
	extraction: AiProbeCheck,
};

export type AiProviderSettings = {
	retrievalBaseUrl: string,
	retrievalApiKeyConfigured: boolean,
	embeddingModel: string,
	embeddingDimensions: number,
	rerankModel: string,
	completionProtocol: CompletionProtocol,
	completionBaseUrl: string,
	completionApiKeyConfigured: boolean,
	chatModel: string,
	extractionModel: string,
};

/**
 *  Complete non-secret provider configuration plus optional write-only secrets.
 *  A missing secret preserves the currently stored value only when its base URL is unchanged.
 */
export type AiProviderSettingsUpdate = {
	retrievalBaseUrl: string,
	retrievalApiKey: string | null,
	embeddingModel: string,
	embeddingDimensions: number,
	rerankModel: string,
	completionProtocol: CompletionProtocol,
	completionBaseUrl: string,
	completionApiKey: string | null,
	chatModel: string,
	extractionModel: string,
};

export type AiRuntimeSettings = {
	automaticEmbeddings: boolean,
	entityExtraction: boolean,
	queryRewriting: boolean,
};

export type AiSearchTrigger = "as_you_type" | "enter_only";

export type Attachment = {
	uuid: string,
	owner: AttachmentOwner,
	blobHash: string,
	filename: string,
	mime: string,
	size: number,
	createdAt: number,
};

export type AttachmentImageDescriptor = {
	attachmentUuid: string,
	blobHash: string,
	byteSize: number,
	height: number,
	mime: AttachmentImageMime,
	previewHeight: number,
	previewWidth: number,
	/**
	 *  Versioned into the immutable resource URL. Bump the cache format when
	 *  preview bytes or sizing rules change so WebView caches cannot retain an
	 *  older derivative under the same URL.
	 */
	resourceVersion: number,
	width: number,
};

export type AttachmentImageMime = "image/gif" | "image/jpeg" | "image/png" | "image/webp";

export type AttachmentOwner = { kind: "page"; uuid: string } | { kind: "block"; uuid: string };

export type Block = {
	uuid: string,
	pageUuid: string,
	parentUuid: string | null,
	orderKey: OrderKey,
	style: BlockStyle,
	markdown: string,
	markdownRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
};

export type BlockContent = {
	markdown: string,
};

/**
 *  Semantic Markdown shape of a block. Task state is part of the style value,
 *  so neither the Rust nor generated TypeScript contract can represent a task
 *  without state or attach task state to a non-task block.
 */
export type BlockStyle = { kind: "paragraph" } | { kind: "bullet" } | { kind: "numbered" } | { kind: "task"; state: TaskState } | { kind: "heading_1" } | { kind: "heading_2" } | { kind: "heading_3" } | { kind: "quote" } | { kind: "code" } | { kind: "divider" };

export type ChatEvent = { kind: "text_delta"; text: string } | { kind: "reasoning"; text: string } | { kind: "tool_start"; id: string; name: string; args: unknown } | { kind: "tool_end"; id: string; result: string } | { kind: "done"; text: string } | { kind: "error"; message: string } | { kind: "usage"; inputTokens: number; outputTokens: number; totalTokens: number } | { kind: "cancelled" };

export type ChatTurn = { role: "user"; text: string } | { role: "assistant"; text: string };

export type CommandError = {
	code: CommandErrorCode,
	message: string,
};

export type CommandErrorCode = "invalid_input" | "not_found" | "conflict" | "unavailable" | "internal";

export type CompletionProtocol = "openai" | "anthropic";

export type ConfigurationAppearance = {
	theme: ConfigurationTheme,
	palette: ConfigurationPalette,
	displayProfile?: ConfigurationDisplayProfile,
	inkColor?: ConfigurationInkColor,
};

export type ConfigurationDisplayProfile = "auto" | "standard" | "eink";

export type ConfigurationImportResult = {
	settings: SettingsSnapshot,
	appearance: ConfigurationAppearance | null,
	connectionVerified: boolean,
	restartRequired: boolean,
};

export type ConfigurationInkColor = "auto" | "color" | "mono";

export type ConfigurationPalette = "iris" | "tidal" | "ember" | "sakura" | "nordic" | "moss";

export type ConfigurationPreview = {
	id: string,
	serverUrl: string | null,
	tokenIncluded: boolean,
	tokenRequired: boolean,
	search: ConfigurationSearch,
	appearance: ConfigurationAppearance | null,
};

export type ConfigurationSearch = {
	enabled: boolean,
	trigger: AiSearchTrigger,
	rerank: boolean,
};

export type ConfigurationTheme = "system" | "light" | "dark";

export type Content = { kind: "page"; record: Page } | { kind: "block"; record: Block };

/**
 *  Opaque revision of one editable content field.
 *  Revisions use the same canonical HLC representation as the sync engine, but
 *  callers can only round-trip the value they received from a read. This keeps
 *  optimistic-concurrency checks typed without exposing HLC parsing to UI code.
 */
export type ContentRevision = string;

export type CreateNoteResult = { status: "created"; note: CreatedNote } | { status: "existing"; page: Page };

export type CreatedNote = {
	page: Page,
	initialBlock: Block,
};

/**  Stable, machine-readable classification for an import diagnostic. */
export type DiagnosticCode = "config_not_found" | "source_directory_not_found" | "unsupported_document_format" | "mixed_indentation" | "non_canonical_indentation" | "non_canonical_continuation_indentation" | "unclosed_fence" | "preserved_macro" | "empty_page_title" | "multiple_page_titles" | "duplicate_page_identity" | "duplicate_page_title" | "duplicate_journal_date" | "duplicate_target_uuid" | "invalid_block_uuid" | "multiple_block_identity_properties" | "duplicate_block_uuid" | "unresolved_page_reference" | "ambiguous_page_reference" | "invalid_block_reference" | "unresolved_block_reference" | "unsupported_nested_wikilink" | "missing_media_source" | "remote_media_blocked" | "unsafe_media_source" | "unsupported_inline_media";

/**  Severity of a non-fatal issue discovered while preparing an import. */
export type DiagnosticSeverity = "info" | "warning" | "error";

/**
 *  Panel technology reported by the platform. There is no CSS media feature for it: `(update: slow)`
 *  is not reported by the e-ink WebView, so the frontend display profile depends on this value.
 */
export type DisplayKind = "eink" | "lcd" | "unknown";

/**
 *  What the panel does with a display-profile request.
 * 
 *  `requested` names the update mode asked for (`"none"` when the standard profile claims none),
 *  `effective_mode` is the mode the view reports afterwards — the ink editor holds a faster mode of
 *  its own while it is open — and `accepted` is false on every platform without a steerable panel.
 */
export type DisplayProfileResult = {
	effectiveMode: string | null,
	requested: string,
	accepted: boolean,
};

/**
 *  Opaque revision of a complete page document projection.
 *  The value is always the canonical lowercase hexadecimal representation of
 *  one SHA-256 digest. Callers may compare and round-trip it, but the digest
 *  framing remains an implementation detail of the document snapshot service.
 */
export type DocumentRevision = string;

/**
 *  One desired semantic unit in a complete document replacement. Existing
 *  units retain their UUID; new units receive a UUIDv7 only after the complete
 *  draft graph has passed validation.
 */
export type DocumentUnitDraft = {
	previousUuid: string | null,
	parentIndex: number | null,
	style: BlockStyle,
	markdown: string,
};

/**
 *  The single frontend invalidation stream for persisted Rust state.
 *  Payloads carry affected IDs when a command can identify them; whole-workspace
 *  replacements (import/sync) deliberately request a full cache refresh.
 */
export type DomainEvent = { kind: "pages_changed"; page_uuids: string[] } | { kind: "blocks_changed"; block_uuids: string[]; container_uuids: string[] } | { kind: "pages_deleted"; page_uuids: string[] } | { kind: "blocks_deleted"; block_uuids: string[]; container_uuids: string[] } | { kind: "graph_changed"; content_uuids: string[] } | { kind: "structure_changed"; block_uuids: string[] } | { kind: "attachments_changed"; owner_uuids: string[] } | { kind: "history_changed" } | { kind: "settings_changed" } | { kind: "sync_status_changed" } | { kind: "server_ai_changed" } | { kind: "workspace_changed" };

export type DomainEventMessage = DomainEvent;

export type GraphEdge = {
	sourceUuid: string,
	targetUuid: string,
	relation: GraphRelation,
};

export type GraphItem = {
	uuid: string,
	kind: ObjectKind,
	label: string,
};

export type GraphRelation = "contains" | "page_link" | "block_reference";

export type GraphSnapshot = {
	items: GraphItem[],
	edges: GraphEdge[],
};

export type HistoryMoveResult = "applied" | "empty" | "skipped";

export type HistoryStatus = {
	undoCount: number,
	redoCount: number,
};

/**
 *  A loss-aware diagnostic suitable for a dry-run report.
 *  `relative_path` is always relative to the selected graph root. Diagnostic
 *  messages never contain note bodies or values from unknown Logseq forms.
 */
export type ImportDiagnostic = {
	severity: DiagnosticSeverity,
	code: DiagnosticCode,
	relativePath: string | null,
	range: SourceRange | null,
	message: string,
	remediation: string | null,
};

export type InkBackground = "plain" | "grid";

export type InkDraft = {
	version: number,
	width: number,
	height: number,
	strokes: InkStroke[],
	background?: InkBackground,
};

/**  An IPC update against an acknowledged immutable document root. */
export type InkDraftPatch = {
	order: string[],
	upserts: InkStroke[],
	background: InkBackground,
};

export type InkDraftSnapshot = {
	draft: InkDraft,
	revision: string | null,
};

export type InkHistorySnapshot = {
	snapshot: InkDraftSnapshot,
	canUndo: boolean,
	canRedo: boolean,
};

export type InkHistoryUpdate = { kind: "snapshot"; history: InkHistorySnapshot } | { kind: "patch"; patch: InkDraftPatch; baseRevision: string | null; revision: string | null; canUndo: boolean; canRedo: boolean };

export type InkNoteStatus = {
	pageUuid: string,
	revision: string | null,
	unpublishedChanges: boolean,
	publicationRequested: boolean,
	baseVersion: string | null,
	heads: InkVersionInfo[],
};

export type InkPoint = {
	x: number,
	y: number,
	pressure: number,
	tiltX: number,
	tiltY: number,
	time: number,
};

export type InkStroke = {
	id: string,
	width: number,
	points: InkPoint[],
};

export type InkVersionInfo = {
	versionUuid: string,
	parents: string[],
	rootHash: string,
	deviceName: string,
	deviceId: string,
	modifiedAtMs: number,
	available: boolean,
};

export type InputCapabilities = {
	stylus: StylusAvailability,
	pressure: boolean,
	tilt: boolean,
	nativeDeviceEvents: boolean,
};

/**
 *  A calendar day without a timezone or time-of-day component.
 *  The private canonical string keeps the Tauri/Specta wire type simple while
 *  construction, serde, and SQLite reads all pass through strict validation.
 */
export type JournalDate = string;

/**
 *  Bounded reverse-chronological Journal page size.
 *  The upper bound keeps desktop and mobile callers from accidentally loading
 *  an unbounded multi-year timeline in one RPC.
 */
export type JournalListLimit = number;

export type LogseqDrawingConversionState = "absent" | "prepared" | "invalid";

export type LogseqImportAvailability = { status: "available" } | { status: "unavailable"; reason: LogseqImportUnavailableReason };

export type LogseqImportBlocker = "empty_import" | "non_empty_workspace" | "blocking_diagnostics" | "alias_collision" | "existing_import_changed" | "background_ai_enabled" | "server_ai_status_unavailable";

export type LogseqImportCommitResult = { status: "applied"; receiptUuid: string; pageCount: number; blockCount: number; aliasCount: number; attachmentCount: number; operationCount: number; openPageUuid: string | null } | { status: "exact_no_op"; receiptUuid: string; openPageUuid: string | null };

export type LogseqImportDestination = "empty" | "existing_receipt" | "not_empty";

export type LogseqImportDiagnosticPage = {
	offset: number,
	total: number,
	diagnostics: ImportDiagnostic[],
};

export type LogseqImportPreview = {
	sessionUuid: string,
	sourceName: string,
	manifestSha256: string,
	destination: LogseqImportDestination,
	blockers: LogseqImportBlocker[],
	canCommit: boolean,
	report: LogseqImportReportSummary,
};

export type LogseqImportProgress = { progress: "indeterminate"; stage: LogseqImportStage } | { progress: "items"; stage: LogseqImportStage; completed: number; total: number };

export type LogseqImportReportSummary = {
	pageCount: number,
	journalCount: number,
	blockCount: number,
	syntheticPreambleBlockCount: number,
	taskCount: number,
	referenceCount: number,
	resolvedReferenceCount: number,
	unresolvedReferenceCount: number,
	mediaReferenceCount: number,
	markdownImageCount: number,
	drawingConversionState: LogseqDrawingConversionState,
	preparedExcalidrawCount: number,
	preservedExcalidrawCount: number,
	localMediaReferenceCount: number,
	inlineMediaReferenceCount: number,
	blockedRemoteMediaReferenceCount: number,
	missingMediaReferenceCount: number,
	blockedUnsafeMediaReferenceCount: number,
	unsupportedMediaReferenceCount: number,
	unreferencedAssetCount: number,
	unreferencedDrawingCount: number,
	preservedBlockUuidCount: number,
	derivedBlockUuidCount: number,
	warningCount: number,
	blockingDiagnosticCount: number,
	diagnosticCount: number,
	diagnosticsTruncated: boolean,
	diagnostics: ImportDiagnostic[],
};

export type LogseqImportStage = "scanning" | "parsing" | "preparing" | "verifying" | "materializing" | "installing" | "committing" | "complete";

export type LogseqImportUnavailableReason = "mobile_platform";

export type MobileSystemInfo = {
	deviceName: string,
	safeArea: SafeAreaInsets,
	displayKind: DisplayKind,
	/**  `None` while no platform publishes a documented color-panel query. */
	colorPanel: boolean | null,
};

export type ObjectKind = "page" | "block";

/**
 *  A lexical, sync-safe sibling ordering key. Keys are fixed-width uppercase
 *  hexadecimal integers, so SQLite TEXT ordering is also numeric ordering.
 */
export type OrderKey = string;

export type Page = {
	uuid: string,
	kind: PageKind,
	title: string | null,
	layout: PageLayout,
	titleRevision: ContentRevision,
	createdAt: number,
	updatedAt: number,
};

/**
 *  One transactionally consistent, deterministic projection of a page's
 *  complete current block tree.
 */
export type PageDocumentSnapshot = {
	pageUuid: string,
	revision: DocumentRevision,
	blocks: Block[],
};

export type PageKind = { kind: "note" } | { kind: "handwriting" } | { kind: "journal"; date: JournalDate };

/**
 *  The durable structural layout of a page. Reading is pane-local
 *  presentation state and deliberately does not cross this boundary.
 */
export type PageLayout = "outline" | "document";

/**
 *  A typed projection over the page catalog. Normal note navigation uses
 *  `Notes`; explicit callers may request Journals or the complete catalog.
 */
export type PageListFilter = "notes" | "journals" | "all";

export type PageRenderSnapshot = {
	document: PageDocumentSnapshot,
	images: AttachmentImageDescriptor[],
};

export type SafeAreaInsets = {
	top: number | null,
	right: number | null,
	bottom: number | null,
	left: number | null,
};

export type SearchHit = {
	content: Content,
	score: number | null,
	snippet?: string | null,
};

export type SearchMode = "fts" | "semantic";

export type SearchTokenMode = "plain" | "prefix";

export type SecretKey = "SYNC_TOKEN";

export type SettingsCapabilities = {
	windowDecorations: boolean,
	windowCornerRounding: boolean,
};

export type SettingsSnapshot = {
	capabilities: SettingsCapabilities,
	windowCornerRadius: number,
	windowDecorationMode: WindowDecorationMode,
	activeWindowDecorationMode: WindowDecorationMode,
	windowDecorationsRequireRestart: boolean,
	windowControlsStyle: WindowControlsStyle,
	/**  What `auto` resolves to on this desktop, and where it puts each button. */
	systemWindowControls: SystemWindowControls,
	startupView: StartupView,
	startupPageUuid: string | null,
	syncServerUrl: string | null,
	aiSearchEnabled: boolean,
	aiSearchTrigger: AiSearchTrigger,
	aiSearchRerank: boolean,
	searchDebugSources: boolean,
	configuredKeys: SecretKey[],
	configPath: string,
};

export type SettingsUpdate = {
	windowCornerRadius: number,
	windowDecorationMode: WindowDecorationMode,
	windowControlsStyle: WindowControlsStyle,
	startupView: StartupView,
	startupPageUuid: string | null,
	syncServerUrl: string | null,
	aiSearchEnabled: boolean,
	aiSearchTrigger: AiSearchTrigger,
	aiSearchRerank: boolean,
	searchDebugSources: boolean,
	apiKeys?: Partial<{ [key in SecretKey]: string }>,
	clearKeys?: SecretKey[],
};

export type SourcePosition = {
	/**  One-based physical line number. */
	line: number,
	/**  One-based Unicode scalar column. */
	column: number,
	/**  Zero-based byte offset in the original UTF-8 source. */
	byteOffset: number,
};

export type SourceRange = {
	start: SourcePosition,
	end: SourcePosition,
};

export type StartupErrorEvent = {
	message: string,
};

export type StartupReadyEvent = null;

export type StartupStatus = { state: "starting"; message: string } | { state: "ready" } | { state: "error"; message: string };

export type StartupView = "dashboard" | "last_session" | "today" | "specific_page";

export type StylusAvailability = "available" | "not_detected" | "unknown";

export type SyncConnectionState = "disabled" | "connecting" | "syncing" | "online" | "offline" | "conflict" | 
/**  Terminal: the server writes a sync format this build cannot read. */
"update_required" | "error";

export type SyncStatus = {
	state: SyncConnectionState,
	serverUrl: string | null,
	lastServerSeq: number,
	pendingOperations: number,
	message: string | null,
	/**
	 *  Sync format the server writes, known only once it has refused this
	 *  build. `None` at every other time, including a plain offline server.
	 */
	serverFormatVersion: number | null,
	/**
	 *  Changes the server refused outright. They are still stored and are sent
	 *  as soon as the user retries them; they just no longer block the queue.
	 */
	quarantinedOperations: number,
	/**  The server's reason for the first held-back change. */
	quarantineReason: string | null,
};

/**  What the running desktop uses. `style` is never [`WindowControlsStyle::Auto`]. */
export type SystemWindowControls = {
	style: WindowControlsStyle,
	left: WindowButton[],
	right: WindowButton[],
};

/**  Durable workflow state carried only by a task block. */
export type TaskState = "todo" | "doing" | "now" | "later" | "done" | "waiting" | "cancelled";

export type WindowButton = "minimize" | "maximize" | "close";

export type WindowControlsStyle = "auto" | "breeze" | "adwaita" | "windows" | "macos" | "minimal";

export type WindowDecorationMode = "native" | "borderless";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

