[package]
name = "notes-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Domain model and SQLite storage engine for tangleaf"

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
chrono.workspace = true
notes-blob.workspace = true
notes-markdown.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
rust-stemmers.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
specta.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
unicode-normalization.workspace = true
uuid.workspace = true
ink-format = { version = "0.1.0", path = "../ink-format" }
specta-typescript.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
proptest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
